import os
from dotenv import load_dotenv
from ship_station import ShipStation, ShipStationOrderResponse

BASEDIR = os.path.abspath(os.path.dirname(__file__))
load_dotenv(os.path.join(BASEDIR, ".env"))

load_dotenv()

# Script used as a playground for testing functionality

ss_api_key = os.getenv("SHIPSTATION_API_KEY", "")
ss_api_secret = os.getenv("SHIPSTATION_API_SECRET", "")
handler = ShipStation(ss_api_key, ss_api_secret)

auth = handler.authorization_header["Authorization"]
z = handler._ShipStation__remove_basic_in_auth_string(auth)
z = handler._ShipStation__decode_b64_auth_string(z)
print(handler.authorize_request(auth))



def get_valid_order_json(order_id: int = 390639144):
    return  {
            "orders": [
                {
                    "orderId": 123,
                    "orderNumber": "00050723",
                    "orderKey": "00050723",
                    "orderDate": "2024-03-19T08:09:13.9000000",
                    "createDate": "2024-03-19T08:09:14.1100000",
                    "modifyDate": "2024-03-19T08:41:07.5930000",
                    "paymentDate": None,
                    "shipByDate": None,
                    "orderStatus": "awaiting_shipment",
                    "customerId": 978231123,
                    "customerUsername": "0035w00003eqknJAAQ",
                    "customerEmail": "jd@does.hoes",
                    "billTo": {
                        "name": "Jane Doe",
                        "company": "Company Name",
                        "street1": None,
                        "street2": "",
                        "street3": "",
                        "city": None,
                        "state": None,
                        "postalCode": None,
                        "country": None,
                        "phone": "(123) 456-7890",
                        "residential": None,
                        "addressVerified": None,
                    },
                    "shipTo": {
                        "name": "Jane Doe",
                        "company": "Company Name",
                        "street1": "213 Maple Street",
                        "street2": "",
                        "street3": "",
                        "city": "NYC",
                        "state": "NY",
                        "postalCode": "22222-2122",
                        "country": "US",
                        "phone": "(132) 456-7890",
                        "residential": True,
                        "addressVerified": "Address validated successfully",
                    },
                    "items": [
                        {
                            "orderItemId": 7893121,
                            "lineItemKey": "0000099999",
                            "sku": "278",
                            "name": "",
                            "imageUrl": "https://google.com/",
                            "weight": {
                                "value": 1.0,
                                "units": "ounces",
                                "WeightUnits": 1,
                            },
                            "quantity": 1,
                            "unitPrice": 3.0,
                            "taxAmount": 0.0,
                            "shippingAmount": 0.0,
                            "warehouseLocation": None,
                            "options": [],
                            "productId": 17122365,
                            "fulfillmentSku": None,
                            "adjustment": False,
                            "upc": None,
                            "createDate": "2024-03-19T08:09:13.9",
                            "modifyDate": "2024-03-19T08:09:13.9",
                        }
                    ],
                    "orderTotal": 11.0,
                    "amountPaid": 0.0,
                    "taxAmount": 0.0,
                    "shippingAmount": 0.0,
                    "customerNotes": None,
                    "internalNotes": "Here are the shipping instructions.",
                    "gift": False,
                    "giftMessage": None,
                    "paymentMethod": None,
                    "requestedShippingService": None,
                    "carrierCode": "ups_walleted",
                    "serviceCode": "ups_ground",
                    "packageCode": "package",
                    "confirmation": "none",
                    "shipDate": None,
                    "holdUntilDate": None,
                    "weight": {"value": 5.5, "units": "ounces", "WeightUnits": 1},
                    "dimensions": None,
                    "insuranceOptions": {
                        "provider": None,
                        "insureShipment": False,
                        "insuredValue": 0.0,
                    },
                    "internationalOptions": {
                        "contents": None,
                        "customsItems": None,
                        "nonDelivery": None,
                    },
                    "advancedOptions": {
                        "warehouseId": 809123978,
                        "nonMachinable": False,
                        "saturdayDelivery": False,
                        "containsAlcohol": False,
                        "mergedOrSplit": True,
                        "mergedIds": [78913890],
                        "parentId": None,
                        "storeId": 123456,
                        "customField1": None,
                        "customField2": None,
                        "customField3": None,
                        "source": None,
                        "billToParty": "my_other_account",
                        "billToAccount": None,
                        "billToPostalCode": None,
                        "billToCountryCode": None,
                        "billToMyOtherAccount": 98765,
                    },
                    "tagIds": None,
                    "userId": None,
                    "externallyFulfilled": False,
                    "externallyFulfilledBy": None,
                    "externallyFulfilledById": None,
                    "externallyFulfilledByName": None,
                    "labelMessages": None,
                },
                {
                    "orderId": 123,
                    "orderNumber": "12345678",
                    "orderKey": "00099999",
                    "orderDate": "2024-03-19T08:09:13.9000000",
                    "createDate": "2024-03-19T08:19:06.2470000",
                    "modifyDate": "2024-03-19T08:40:57.4930000",
                    "paymentDate": None,
                    "shipByDate": None,
                    "orderStatus": "awaiting_shipment",
                    "customerId": 349875,
                    "customerUsername": "0035w00003eqknJAAQ",
                    "customerEmail": "jd@does.hoes",
                    "billTo": {
                        "name": "Jane Doe",
                        "company": "Company Name",
                        "street1": "213 Maple Street",
                        "street2": "",
                        "street3": "",
                        "city": "NYC",
                        "state": "PA",
                        "postalCode": "22222-2222",
                        "country": "US",
                        "phone": "(123) 456-7890",
                        "residential": None,
                        "addressVerified": None,
                    },
                    "shipTo": {
                        "name": "Jane Doe",
                        "company": "Company Name",
                        "street1": "213 Maple Street",
                        "street2": "",
                        "street3": "",
                        "city": "NYC",
                        "state": "NY",
                        "postalCode": "22222-2222",
                        "country": "US",
                        "phone": "(123) 456-7890",
                        "residential": True,
                        "addressVerified": "Address validated successfully",
                    },
                    "items": [
                        {
                            "orderItemId": 98765432,
                            "lineItemKey": "000001234",
                            "sku": "123",
                            "name": "",
                            "imageUrl": "",
                            "weight": {
                                "value": 1.5,
                                "units": "ounces",
                                "WeightUnits": 1,
                            },
                            "quantity": 1,
                            "unitPrice": 8.0,
                            "taxAmount": None,
                            "shippingAmount": None,
                            "warehouseLocation": None,
                            "options": [],
                            "productId": 123456,
                            "fulfillmentSku": None,
                            "adjustment": False,
                            "upc": None,
                            "createDate": "2024-03-19T08:19:06.467",
                            "modifyDate": "2024-03-19T08:19:06.467",
                        }
                    ],
                    "orderTotal": 0.0,
                    "amountPaid": 0.0,
                    "taxAmount": 0.0,
                    "shippingAmount": 0.0,
                    "customerNotes": None,
                    "internalNotes": "Here are the shipping instructions.",
                    "gift": False,
                    "giftMessage": None,
                    "paymentMethod": None,
                    "requestedShippingService": None,
                    "carrierCode": "ups_walleted",
                    "serviceCode": "ups_ground",
                    "packageCode": "package",
                    "confirmation": "none",
                    "shipDate": None,
                    "holdUntilDate": None,
                    "weight": {"value": 1.5, "units": "ounces", "WeightUnits": 1},
                    "dimensions": {
                        "units": "inches",
                        "length": 20.0,
                        "width": 2.0,
                        "height": 2.0,
                    },
                    "insuranceOptions": {
                        "provider": None,
                        "insureShipment": False,
                        "insuredValue": 0.0,
                    },
                    "internationalOptions": {
                        "contents": None,
                        "customsItems": None,
                        "nonDelivery": None,
                    },
                    "advancedOptions": {
                        "warehouseId": 1234,
                        "nonMachinable": False,
                        "saturdayDelivery": False,
                        "containsAlcohol": False,
                        "mergedOrSplit": True,
                        "mergedIds": [],
                        "parentId": 34567890,
                        "storeId": 123456,
                        "customField1": None,
                        "customField2": None,
                        "customField3": None,
                        "source": None,
                        "billToParty": "my_other_account",
                        "billToAccount": None,
                        "billToPostalCode": None,
                        "billToCountryCode": None,
                        "billToMyOtherAccount": 12345,
                    },
                    "tagIds": None,
                    "userId": None,
                    "externallyFulfilled": False,
                    "externallyFulfilledBy": None,
                    "externallyFulfilledById": None,
                    "externallyFulfilledByName": None,
                    "labelMessages": None,
                },
            ],
            "total": 2,
            "page": 1,
            "pages": 1,
        }