{
    "Date": "Tue, 20 Feb 2024 18:56:52 GMT",
    "Content-Type": "application/json; charset=utf-8",
    "Content-Length": "1503",
    "Connection": "keep-alive",
    "X-Rate-Limit-Limit": "40",
    "X-Rate-Limit-Reset": "8",
    "X-Rate-Limit-Remaining": "38",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "expires": "-1",
    "server": "Microsoft-IIS/10.0",
    "x-aspnet-version": "4.0.30319",
    "x-powered-by": "ASP.NET",
}
